package com.io.loopit.paysheet.model.enums;

import lombok.Getter;

@Getter
public enum Profession {
    CAIXA,
    ATENDENTE_DE_BALCAO,
    REPOSITOR,
    FISCAL_DE_LOJA,
    AUXILIAR_DE_LIMPEZA,
    ACOUGUEIRO,
    PADEIRO,
    CONFEITEIRO,
    GERENTE_DE_LOJA,
    ASSISTENTE_DE_COMPRAS,
    ESTOQUISTA,
    ENCARREGADO_DE_SETOR,
    VENDEDOR,
    AUXILIAR_ADMINISTRATIVO,
    OPERADOR_DE_EMPILHADEIRA,
    AUXILIAR_DE_LOGISTICA,
    ENTREGADOR,
    SEGURANCA,
    AUXILIAR_DE_CAIXA,
    AUXILIAR_DE_COZINHA;
}