server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

spring:
  application:
    name: loopit.paysheet

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
    hikari:
      connection-timeout: ${DB_TIMEOUT}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
      show-sql: ${DB_SHOW_SQL}

  datasource-secondary:
    url: ${DB_SECONDARY_URL}
    username: ${DB_SECONDARY_USER:root}
    password: ${DB_SECONDARY_PASSWORD}
    driver-class-name: ${DB_SECONDARY_DRIVER_CLASS}
    hikari:
      connection-timeout: ${DB_SECONDARY_TIMEOUT}
      maximum-pool-size: ${DB_SECONDARY_MAXIMUM_POOL_SIZE}
    hibernate:
      ddl-auto: ${DB_SECONDARY_DDL_AUTO}
      show-sql: ${DB_SECONDARY_SHOW_SQL}

  jpa:
    open-in-view: ${DB_OPEN_VIEW}

  aws:
    credentials:
      serviceEndpoint: ${AWS_ENDPOINT}
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucketName: ${AWS_BUCKET_NAME}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: WARN
    org.springframework.security.web.DefaultSecurityFilterChain: WARN
    org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean: WARN
    com.zaxxer.hikari.HikariDataSource: WARN
    com.zaxxer.hikari.pool.HikariPool: WARN
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: WARN
    org.springframework.data.repository.config.RepositoryConfigurationDelegate: WARN
    org.apache.catalina.core.StandardService: WARN
    org.hibernate.jpa.internal.util.LogHelper: WARN
    org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: WARN
    org.hibernate.Version: WARN
    org.hibernate.cache.internal.RegionFactoryInitiator: WARN
    org.springframework.orm.jpa.persistenceunit.SpringPersistenceUnitInfo: WARN
    org.apache.catalina.core.StandardEngine: WARN
